### ISSUE TITLE
No color graphics in Ubuntu 14.04

### ISSUE THREAD

**Issue by dschalk** [mobxjs/mobx-react-devtools#1]
I can see in my console log that start and finish times are being observed, but I am not seeing color graphics or any new display in the browser. I checked this with Chrome, Firefox, and Opera on my Ubuntu 14.04 box. The web page I am testing loads from http://schalk.ninja .

**Comment by mweststrate** [comment]
@dschalk 

I'm still updating docs, but did you already switch to `reactiveComponent` from `mobservable` to `mobservable-react`? I've splitted the `mobservable` package into two, but left the old version in `mobserable` for backward compatibility. The new one contains the dev tool support though.

**Comment by dschalk** [comment]
I used the decorator method with mobservable-react. It's working now. Thanks.
