### ISSUE TITLE
error msg "propTypes is not defined"  in 6.1.0

### ISSUE THREAD

**Issue by pdeva** [mobxjs/mobx-react-devtools#111]
Getting this error msg:

![image](https://user-images.githubusercontent.com/3190176/53775137-2eab9200-3ea6-11e9-92bd-6dfd90182092.png)

Update:
This seems to be a bug in devtools 6.1.0.
reverting to 6.0.3 fixes this.

**Comment by LightGlobal** [comment]
I get the same error

**Comment by mweststrate** [comment]
Should be fixed in 6.1.1!

**Comment by richardaum** [comment]
When is 6.1.1 being released?

**Comment by Ky6uk** [comment]
@richardaum it has been released already.
