### ISSUE TITLE
Can this be attached to any dom outside the react app root?

### ISSUE THREAD

**Issue by msuntharesan** [mobxjs/mobx-react-devtools#13]
similar to [`redux-devtools`](https://github.com/gaearon/redux-devtools).
Because I want to leverage webpack `code splitting` with this. Something like this

``` js
if (__DEVTOOLS__) {
  require.ensure([], require => {
    const DevTools = require('mobx-react-devtools');
    ReactDom.render((
      <DevTools />
    ), document.getElementById('devtools'));
  }, 'mobx-devtools');
}
```

**Comment by mweststrate** [comment]
That should work fine, as long as that part of the DOM isn't shared with the 'real' react component root.
