### ISSUE TITLE
Console logging needs to be turned off and off again before working with server-side rendering

### ISSUE THREAD

**Issue by brownish** [mobxjs/mobx-react-devtools#15]
When using server-side rendering, the console logging button is blue (should be active) but nothing is logging. If I turn it off and back on again logging then works. Any way to have logging automatically work without manually doing this?

**Comment by mweststrate** [comment]
Fixed in 4.0.3. Tnx @andykog!

**Comment by brownish** [comment]
Works now. Thanks!
