### ISSUE TITLE
Server rendering

### ISSUE THREAD

**Issue by maxs15** [mobxjs/mobx-react-devtools#17]
Hi,

First of all awesome work on mobx guys, my code is getting some much cleaner ! :)
I'm having some issue with the server side rendering of mobx-react-devtools, it looks like the style properties aren't generated in the same order on the server/client.

Because of that I'm getting this issue:

```
React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) d="237"><div style="position:fixed;heigh
 (server) d="237"><div style="border-style:solid;f
```

Do you think it could be an issue related to radium ?
There is some weird properties in the style as well:

```
panel:[object Object];button:[object Object];button-log:[object Object];button-log-active:[object Object];button-updates:[object Object];button-updates-active:[object Object];button-graph:[object Object];button-graph-active:[object Object]
```

Here is the generated markup:
Server:

```
<div style="position:fixed;height:26px;background-color:#fff;color:rgba(0, 0, 0, 0.8);border-radius:0 0 2px 2px;border-style:solid;border-width:0 1px 1px;border-color:rgba(0, 0, 0, 0.1);z-index:65000;font-family:Helvetica, sans-serif;display:flex;padding:0 5px;panel:[object Object];button:[object Object];button-log:[object Object];button-log-active:[object Object];button-updates:[object Object];button-updates-active:[object Object];button-graph:[object Object];button-graph-active:[object Object];top:0px;right:20px;" data-reactid="238">
```

Client:

```
<div style="border-style:solid;font-family:Helvetica, sans-serif;panel:[object Object];top:0px;padding:0 5px;border-radius:0 0 2px 2px;color:rgba(0, 0, 0, 0.8);position:fixed;button:[object Object];display:flex;right:20px;button-graph:[object Object];border-color:rgba(0, 0, 0, 0.1);button-graph-active:[object Object];button-updates-active:[object Object];border-width:0 1px 1px;background-color:#fff;z-index:65000;button-log-active:[object Object];button-updates:[object Object];height:26px;button-log:[object Object];" data-reactid="238">
```

Thanks

**Comment by andykog** [comment]
@maxs15, hi!
1. `npm list | grep mobx-react-devtools` in your project's folder gives version `4.0.5`?
2. What browser are you using?
3. Can you try passing undocumented prop `userAgent` when using server rendering like this:

``` jsx
<DevTool userAgent={req.headers['user-agent']} />
```

(req here is express [Request](http://expressjs.com/en/api.html#req))

**Comment by andykog** [comment]
4 . What version of nodejs are you using?

**Comment by maxs15** [comment]
1. Yes I'm using the last version (4.0.5)
2. I'm using chrome 50.0.2661.94
3. Just tried using the userAgent but didn't change anything
4. I'm using node 5.6.0

**Comment by andykog** [comment]
Strange, could you please try https://github.com/mobxjs/mobx-react-devtools if the problem occurs there. (`npm install; npm start`)

**Comment by andykog** [comment]
I'm sorry, I mean https://github.com/mobxjs/mobx-react-todomvc

**Comment by maxs15** [comment]
Good idea ! And apparently no issue there..
I'll try to investigate the differences I have on my project, will let you know if I find anything.
Thanks for the help Andy
