### ISSUE TITLE
Cannot find module css-loader

### ISSUE THREAD

**Issue by thunderkid** [mobxjs/mobx-react-devtools#2]
I've installed this for a simple (typescript) project. I get a compilation error saying:
 Cannot find module '!!./../node_modules/css-loader/index.js!./devtools.css' from \my\path\node_modules\mobservable-react-devtools.
I also tried installing css-loader, but that makes no difference.
Am I supposed to do anything else beyond just the npm install and using require in my main .ts file? Thanks.

**Comment by mweststrate** [comment]
You're right, there were still webpack artifacts in the build, so building with something else would probably break it. I've just published 2.0.2, does that version fix the issue?

**Comment by thunderkid** [comment]
Well, it fixed the compilation issue. But I'm not sure it's actually doing anything. I was expecting to see little icons by my table showing how many times each item had been rendered, but nothing's appearing. The console log isn't showing anything either. I've also tried require in the actual tsx file doing the rendering, but still nothing appears on screen.

**Comment by mweststrate** [comment]
Could you check whether the toolbar is in the the dom at the end of the
body (class: mobservable-devtools-wrapper)? just an import it is enough:
`import "mobservable-react-devtools"`. Make sure you don't import it under
a name, because then the compiler will optimize it away as you don't
actively use it in the file.

**Comment by thunderkid** [comment]
No, I'm not seeing the toolbar in the dom. However, the compiled js does contain mobservable-react-devtools code, and so does the css. It's just not in the dom.

**Comment by mweststrate** [comment]
Could you try 2.0.4? I've added some logging to the startup. I also added the devtools to the typescript-react boilerplate project, so you could compare your setup with that one as well: https://github.com/mweststrate/mobservable-react-typescript

**Comment by thunderkid** [comment]
I tried 2.0.4. Still nothing appearing. In the console I get an error message saying: 

```
Initalized mobservable-react-devtools, but the toolbar has been removed from the DOM. Was React mounted on document.body?
```

I do have react mounted on the document body. I also tried wrapping it in a 'container' div, but that makes no difference.

And when I try to clone and run your boilerplate project (on Windows 8) it fails with the following error log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.14.3
3 info using node@v4.1.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild mobservable-react-typescript@1.0.0
6 info build mobservable-react-typescript@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info mobservable-react-typescript@1.0.0 Failed to exec build script
9 verbose stack Error: mobservable-react-typescript@1.0.0 build: `browserify src/index.tsx -p tsify > public/js/bundle.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid mobservable-react-typescript@1.0.0
11 verbose cwd C:\Users\dog\Documents\MobservableToy\mobservable-react-typescript
12 error Windows_NT 6.3.9600
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
14 error node v4.1.0
15 error npm  v2.14.3
16 error code ELIFECYCLE
17 error mobservable-react-typescript@1.0.0 build: `browserify src/index.tsx -p tsify > public/js/bundle.js`
17 error Exit status 1
18 error Failed at the mobservable-react-typescript@1.0.0 build script 'browserify src/index.tsx -p tsify > public/js/bundle.js'.
18 error This is most likely a problem with the mobservable-react-typescript package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     browserify src/index.tsx -p tsify > public/js/bundle.js
18 error You can get their info via:
18 error     npm owner ls mobservable-react-typescript
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by mweststrate** [comment]
Not mounting react on document.body should fix it I think, unless something
else is clearing the body as well. Can you double check that you really
aren't still mounting on the document.body node? You can simply check that
using the react devtools or by checking whether a react-id attribute is
present. Note that react itself should warn you as well when mounting
document.body.

Ahh.. windows :) I'll fixed the build script for windows

**Comment by mweststrate** [comment]
Which browser are you using?

**Comment by thunderkid** [comment]
So, I'm using Chrome Version 45.0.2454.99 m.
My main ts file basically just does:

```
import 'mobservable-react-devtools';
$(document).ready(function() {
    ReactDOM.render(
        <ProductTable vMod={new TestVM()} />,
        document.getElementById('teststorething')
    );
});
```

My DOM is showing in chrome's elements tab as:

``` ....
  <body>
    ....
    <div id="teststorething">
        <div data-reactid=".0">
           (my react table)
        </div>
    </div>
  </body>
```

So it seems I'm not mounting on the body, but I have no toolbars. Is that what you mean?

**Comment by mweststrate** [comment]
Hmm.. intriguing. Could you quickly try whether removing the jquery ready
function makes a difference? Or doing the import after the ReactDOM.render
using `require('mobservable-react-devtools');`? If changing either of these
is hard I'll try to rebuild your use-case.

**Comment by thunderkid** [comment]
Using `require('mobservable-react-devtools')` below the render makes no difference.
If I take out the jquery ready function altogether, I just get the error:
`_registerComponent(...): Target conatiner is not a DOM element.`
So instead, I've tried replacing it with `window.onload = function() { ReactDOM.render(...`
That makes no difference either.

**Comment by mweststrate** [comment]
Ok thanks for the info, I'm gonna try to reproduce this with a similar setup.

**Comment by mweststrate** [comment]
I tried to mimic your setup in the test project you provided earlier for the mobservable-react issue. Could you verify whether this setup works for you and compare it with your own setup? I wasn't able to reproduce the issue so far.
[more-animals.zip](https://github.com/mweststrate/mobservable-react-devtools/files/67029/more-animals.zip)

**Comment by thunderkid** [comment]
Ok, thanks. That showed me what was wrong. I've been putting my `<script src="js/bundle.js"></script>` at the bottom of the `<header>` block, which doesn't work. Putting it at the bottom of the `<body>` block instead makes it work.
