### ISSUE TITLE
Warning: Unknown prop `_radiumDidResolveStyles` on <div> tag.

### ISSUE THREAD

**Issue by osenvosem** [mobxjs/mobx-react-devtools#23]
If I remove `<DevTools />` component there is no error.

![screen shot 2016-07-04 at 06 31 36](https://cloud.githubusercontent.com/assets/6762673/16550274/2676949e-41b1-11e6-876f-7b0d246d9d99.png)

**Comment by jameswyse** [comment]
Seems this is a new warning in React v15.2.0, usually caused by forgetting to remove non-standard props before spreading them on a standard HTML element like `<div>`.

See related issue on Radium: https://github.com/FormidableLabs/radium/issues/759 and associated pull request: https://github.com/FormidableLabs/radium/pull/761

**Comment by osenvosem** [comment]
@jameswyse ok, thanks.

**Comment by georgiik-welldone** [comment]
So please, publish new version with fixes from radium. Coz published version contains old version of code.

**Comment by andykog** [comment]
@georgiik-welldone, what do you mean 'old version'? mobx-react-devtools requires the latest version of radium, 0.17.1 https://github.com/mobxjs/mobx-react-devtools/blob/master/package.json#L34

**Comment by andykog** [comment]
I think, we can drop radium for styles. May be I'll do it today.

**Comment by georgiik-welldone** [comment]
@andykog sorry my bad, new changes from radium haven't come up yet. Can we rely on radium's master branch?

**Comment by andykog** [comment]
@georgiik-welldone, npm can't rely on any github branch if there is no precompiled lib provided. Moreover, I'm not sure this bug is already fixed in master.

**Comment by andykog** [comment]
Dropped radium, the warning won't appear in the next version of `mobx-react-devtools`

**Comment by mweststrate** [comment]
Released as 4.2.1
