### ISSUE TITLE
Chrome console dark theme coloring

### ISSUE THREAD

**Issue by mvestergaard** [mobxjs/mobx-react-devtools#25]
This is a minor thing, but is there any chance the blue log color could be lightened a bit, it looks very harsh in Chrome's dark theme

<img width="766" alt="screen shot 2016-07-15 at 20 37 47" src="https://cloud.githubusercontent.com/assets/2027834/16884882/27d8c356-4acc-11e6-81e0-0db1c551c395.png">

**Comment by mvestergaard** [comment]
Maybe use teal instead

**Comment by mvestergaard** [comment]
Here's teal in both light and dark

<img width="398" alt="screen shot 2016-07-15 at 20 41 47" src="https://cloud.githubusercontent.com/assets/2027834/16884974/a56de724-4acc-11e6-9fbc-56d32b967f34.png">
<img width="248" alt="screen shot 2016-07-15 at 20 42 11" src="https://cloud.githubusercontent.com/assets/2027834/16884977/aa4722d8-4acc-11e6-85c6-f195a8c9b2b8.png">

**Comment by mvestergaard** [comment]
Or maybe "dodgerblue" :)

<img width="276" alt="screen shot 2016-07-15 at 20 50 40" src="https://cloud.githubusercontent.com/assets/2027834/16885219/dca3fe9e-4acd-11e6-9e16-4ae746769d59.png">
<img width="266" alt="screen shot 2016-07-15 at 20 50 24" src="https://cloud.githubusercontent.com/assets/2027834/16885223/df309dca-4acd-11e6-9ff5-7681ba5ba50d.png">

**Comment by andykog** [comment]
@mvestergaard, good idea, made green color a bit lighter as well.

**Comment by andykog** [comment]
Published as `4.2.3`
