### ISSUE TITLE
CSS Style

### ISSUE THREAD

**Issue by corintho** [mobxjs/mobx-react-devtools#3]
I would suggest adding a high value 'z-index' property to the class: `.mobservable-devtools-wrapper` or add instructions in the documentation warning that it may remain hidden under a fixed header.
In my case, it was hidden under a fixed header I have and I added the z-index in a CSS file in my project to fix it.

**Comment by mweststrate** [comment]
Thanks for pointing this out! I will increase the number.

**Comment by mweststrate** [comment]
Fix published as 2.0.5
