### ISSUE TITLE
Optimize logger output for firefox

### ISSUE THREAD

**Issue by andykog** [mobxjs/mobx-react-devtools#31]
Eyes are bleeding:
![screen shot 2016-08-24 at 17 17 32](https://cloud.githubusercontent.com/assets/6760207/17933954/ba2e0ed4-6a1e-11e6-8797-7a28c145cdc9.png)

**Comment by timothyallan** [comment]
Hahah came here to whine about Microsoft Edge doing the same.
![screen shot 2016-09-03 at 10 16 24 pm](https://cloud.githubusercontent.com/assets/1995135/18229009/2021b6d4-7224-11e6-88df-cbc9088b2320.png)

**Comment by wkillerud** [comment]
Firefox logs now render properly (screenshot taken in Firefox 63.0b11). The console has seen some updates since this issue was created 👍 

![image](https://user-images.githubusercontent.com/1223410/46685129-fce31780-cbf4-11e8-880f-27a0f20bc97d.png)

Edge is still behaving as pictured above.
