### ISSUE TITLE
Console statements in `componentWillReact` do not work if devtools logging is enabled

### ISSUE THREAD

**Issue by bjrnt** [mobxjs/mobx-react-devtools#34]
A `componentWillReact` function such as

```
componentWillReact() {
  console.log('Reacting!');
}
```

will not do anything if the devtools logging is enabled. Instead, messages such as

```
updated 'MyComponent@2.value': 1232321 (was: 123232)
mobx.js?6a62:1123 reaction 'MyComponent#0.render()'
```

will be printed.

After disabling the devtools logging, `Reacting!` is printed as expected.

This caused a bit of confusion for us, as it seemed like `componentWillReact` was not being called properly. Is this a bug or intended?

**Comment by mweststrate** [comment]
@bjrnt the messages should be printed, but inside the console group that is running at the moment of logging and not necessarily at the top level

**Comment by bjrnt** [comment]
@mweststrate Ah, indeed they are. Thank you! 

I think this behavior is still different from what one would expect, though. It seems like log group messages give a summary of what happened, e.g. `updated 'MyComponent@2.value': 12 (was: 1)`, which then can be expanded to see more details about the event. Including information within the log group which is not present in the summary makes the log group a counter-intuitive place to look. Maybe this could be clarified through additional documentation, or adding something to the log group message.

**Comment by mweststrate** [comment]
Added some documentation for this. Thanks for reporting
