### ISSUE TITLE
Support dependency trees for higher-order components

### ISSUE THREAD

**Issue by maxdeviant** [mobxjs/mobx-react-devtools#38]
It would be very useful (and necessary, in my opinion) to support being able to view the dependency trees for higher-order components.

Currently, if you select a component wrapped with higher-order components in the dependency tree viewer, it will only show you the top-most higher-order component. This is usually not very helpful, as the most important dependency tree is usually in the base component.

It would be nice to have a way of paging through the different components in the dependency tree viewer.

**Comment by mweststrate** [comment]
A simpler solution might be to show the trees in the same overview, with a new root node. Would you be interested to take a shot at it?

**Comment by maxdeviant** [comment]
Sure, I can take a look at it. Was poking around in the code a bit this morning, and it seemed fairly straightforward.
