### ISSUE TITLE
[Question] - Clarification on log terminology for actions

### ISSUE THREAD

**Issue by dsifford** [mobxjs/mobx-react-devtools#39]
Hi there, 

Quick question for ya. This is probably going to be super obvious once you answer, but I just can't seem to figure out what the `@xxx` after some actions is supposed to mean (see image below)

Can you clarify? I'd imagine this to be line number, but they don't match up (at least not in the source maps).

Thanks in advance.

![image](https://cloud.githubusercontent.com/assets/5240018/18603154/3698e8a6-7c3d-11e6-97a5-0a639f6619f2.png)

**Comment by mweststrate** [comment]
@dsifford it is the instance number, basically a linear increasing to allow distinguish different instances of the same type.

**Comment by dsifford** [comment]
Ah, I see!

So, to be clear, in the screenshot I posted earlier, `ReferenceList@10` was a single action instance composed of the three sub-actions (`toggleMenu`, `reset`, and `clearSelection`)?

Correct me if I'm wrong. Otherwise, thanks so much for the clarification and your work on this. 👍
