### ISSUE TITLE
hightlightTimeout doesn't seem to be passed on to Panel

### ISSUE THREAD

**Issue by Mikk36** [mobxjs/mobx-react-devtools#41]
With testing and looking at the code (src/DevTool.js) it doesn't seem like the this.props.hightlightTimeout is ever passed on to Panel component.
Not to mention that it has a typo in it.

**Comment by andykog** [comment]
@Mikk36, thanks for noticing, fixed in `mobx-react-devtools@4.2.7`

**Comment by Mikk36** [comment]
You should also update the readme to reflect the fixed prop name.

**Comment by andykog** [comment]
Oh, you are right
