### ISSUE TITLE
publish fixed ts definition

### ISSUE THREAD

**Issue by panjiesw** [mobxjs/mobx-react-devtools#43]
Hi,
I'm sorry to bring this up here.

Since #42 is merged, would you publish a new version to npm? We heavily use typescript with strict null check and this prevent successful build without manually hack into installed mobx-react-devtools in node_modules.

Thanks

**Comment by andykog** [comment]
Published as `mobx-react-devtools@4.2.9`

**Comment by panjiesw** [comment]
Thanks @andykog much appreciated
