### ISSUE TITLE
Couldn't find preset 'es2015' relative to directory "node_modules\mobx-react-devtools"

### ISSUE THREAD

**Issue by ghost** [mobxjs/mobx-react-devtools#49]
Hi,

I did the following:

react-native init projectname
cd projectname
npm install --save-dev rnpm-plugin-windows
react-native windows

npm install mobx --save
npm install mobx-react --save
npm install --save-dev mobx-react-devtools

Opened up index.windows.js

Added to the top of file
import DevTools from 'mobx-react-devtools';

Added inside the <View> Component
<DevTools />

Ran react-native run-windows

And then once it launches the windows tool, i get an error saying:
Couldn't find preset 'es2015' relative to directory "node_modules\mobx-react-devtools"

Unfortunately I haven't set up my computer for Android development yet so I'm not sure if it's a windows only issue.

I tried running npm install babel-preset-es2015 --save --no-bin-links as suggested by other forums like https://github.com/laravel/elixir/issues/354

But nothing seems to help.

Any ideas why this would be happening?

Thanks
Cherie

**Comment by mweststrate** [comment]
the devtools only support react in browser environments. mobx-logger should
work for RN as well though

Op do 8 dec. 2016 03:21 schreef kwancherie <notifications@github.com>:

**Comment by ghost** [comment]
Thanks!
