### ISSUE TITLE
DevTools position on page

### ISSUE THREAD

**Issue by mromanoff** [mobxjs/mobx-react-devtools#52]
How I can position DevTools in other view port location opposed to a right-top corner? for example DevTools container blocking navigation in my app. I wish I could set props on DevTools component for example: <DevTools className="Position-bottomRight" style={{bottom: '10px', right: '10px'}} />

**Comment by AoDev** [comment]
You can pass a `position` prop. It's in the readme.

Or you can see the code: [Panel position](https://github.com/mobxjs/mobx-react-devtools/blob/master/src/Panel/index.jsx#L29)

**Comment by andykog** [comment]
`<DevTools style={...} />` might be a good alternative for current `<DevTools position={...} />`

**Comment by mromanoff** [comment]
'position' prop will do work for me just fine.
