### ISSUE TITLE
Create blank component for production

### ISSUE THREAD

**Issue by MocanuMarius** [mobxjs/mobx-react-devtools#58]
Hi , when using React you'd like the component to simply not be imported or to render a blank return null when it runs in a production environement e.g. NODE_ENV = "production" . It's very cumbersome to render it conditionally, and even harder inside a react component.

Do you want me to do a PR on this ?

**Comment by suprise** [comment]
Hi，@MocanuMarius  ，may be you can try this [simple method](https://github.com/mobxjs/mobx-react-devtools/issues/40) or try [chrome extension](https://github.com/mobxjs/mobx-react-devtools/pull/50)

**Comment by andykog** [comment]
@MocanuMarius, the poblem is that if devTools simply implement this check inside it's component's render(), we may end up people loading all the code in production (that will increase production bundle size). If you have an idea on how to deal with that — feel free to PR :-)

**Comment by rifler** [comment]
you could provide "module" field in package.json, so webpack 2+ will prefer es6 modules build instead of cjs

example from mst
https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mobx-state-tree/package.json#L5-L7

**Comment by Ky6uk** [comment]
It seems to be fixed in https://github.com/mobxjs/mobx-react-devtools/pull/95

Now you can use something like `{process.env.NODE_ENV === 'production' || <DevTools />}` w/o side effects. But I wasn't testing it yet.
