### ISSUE TITLE
Styling doesn't support bottom placement

### ISSUE THREAD

**Issue by janaagaard75** [mobxjs/mobx-react-devtools#60]
This is pretty minor.

I prefer placing the devtools panel at the bottom right of the browser window, because I find that it can get in the way of the web app behind it, when the panel is in the top right corner. It's easy to position the panel by defining `bottom` and `right`, but the result in top notch, because the panel doesn't have a border and rounded corners at the top of it.

```html
<DevTools position={{ bottom: 0, right: 20 }}/>
```

One solution would be to have the border and border radius on all four corners of the panel, and then position the panel a couple of pixels off screen. Somewhat like this: https://github.com/janaagaard75/mobx-react-devtools/commit/6a90dd46246b49c52fcda664c1cc23045625dbe8

**Comment by mweststrate** [comment]
PR would be welcome
