### ISSUE TITLE
Move 'prop-types' to peerDependencies

### ISSUE THREAD

**Issue by le0nik** [mobxjs/mobx-react-devtools#62]
Right now using `mobx-react-devtools` triggers a warning in console: 

`Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them. Read more at http://fb.me/use-check-prop-types`

It's due to a bug in `prop-types`<15.5.10 which was fixed in this commit https://github.com/facebook/prop-types/commit/118249e4fd10ed3dc6298111869551def90dadde

`mobx-react-devtools` however is prebundled with an older version of `prop-types` which doesn't contain this fix.

I think it should use the version of `prop-types` installed by the user instead of adding one in it's package.

**Comment by bernex** [comment]
`Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them.`

same error with last version....

**Comment by andykog** [comment]
I don't like adding another peerDependency for this plus It's not the recommended way: https://github.com/facebook/prop-types#how-to-depend-on-this-package (see also https://github.com/facebook/prop-types/issues/4)
So I've simply updated prop-types and removed definition of NODE_ENV (it was shipped with NODE_ENV=production)
Released as 4.2.13
@le0nik, @bernex, could you confirm that the warning is gone?

**Comment by le0nik** [comment]
@andykog can confirm that it's fixed in 4.2.13

**Comment by bernex** [comment]
@andykog confirmed!
