### ISSUE TITLE
Production mode

### ISSUE THREAD

**Issue by hyperknot** [mobxjs/mobx-react-devtools#66]
How do you disable / not include this module in production setup? I tried to look it up in the docs but I couldn't find anything.

I'm using an ejected create-react-app, so it automatically adds:
```
process.env.BABEL_ENV = 'production'
process.env.NODE_ENV = 'production'
```
in the build script. Is there any way to conditionally load mobx-devtools based on these variables for example?

**Comment by hyperknot** [comment]
Redux-devtools has a section in it's docs, is it the recommended method for this module as well?
https://github.com/gaearon/redux-devtools/blob/master/docs/Walkthrough.md#exclude-devtools-from-production-builds

**Comment by hyperknot** [comment]
Actually, create-react-app already includes DefinePlugin by default, so making a conditional import is as simple as 
```
{process.env.NODE_ENV === 'development' ? <DevTool /> : null}
```

**Comment by moos** [comment]
Typo above: `<DevTool`**s** `  />`

**Comment by alexhtech** [comment]
I think you need to import the component of DevTools from node_module if NODE_ENV is development only. Something like this...

```js

const isDev = process.env.NODE_ENV === 'development'

if(isDev){
const DevTools = require('mobx-react-devtools')
}

and somewhere in your jsx you need to render it if isDev ...

render(){
  return (
    <div>
      {isDev && <DevTools/>}
    </div>
}

```

It will exclude mobx devtools from production build

**Comment by hyperknot** [comment]
Afaik you cannot do this with ES6 imports, can you?

**Comment by moos** [comment]
I believe that's correct -- `import`s must be before any other statements.  But `require` fills the gap nicely.

**Comment by alexhtech** [comment]
This is just for example. You can implement this feature exactly like you want :) up to you.

**Comment by gilesbutler** [comment]
Hey @alexolefirenko, using your code I get the following error...

```Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.```

Any ideas?

**Comment by aap82** [comment]
@gilesbutler  use  `const DevTools = require('mobx-react-devtools').default`

**Comment by gilesbutler** [comment]
Thanks @aap82 that fixed it, unfortunately the devtools are still appearing in my build though hmm

**Comment by oleeeg** [comment]
I guess for now the only way to get the 'mobx-react-devtools' module out of the production build would be Code splitting. Something like:
```javascript
  componentDidMount() {
    if (process.env.NODE_ENV === 'development') {
      import('mobx-react-devtools').then(module => {
        this.setState({ DevTools: module.default });
      });
    }
  }

...

  render() {
    const { DevTools: DevToolsCmp } = this.state;
    return (
        <div>
          {DevToolsCmp && <DevToolsCmp />}
        </div>
    );
  }
```

Please correct me if I'm wrong.

**Comment by alexhtech** [comment]
@gilesbutler I don't know why it is still appearing in your build, but for me this lines works properly

```
// src/index.js
...
if (process.env.NODE_ENV !== 'production') {
    require('mst-middlewares').connectReduxDevtools(require('remotedev'), store)
}
...
```

Just I'm using reduxdevtools for my project, but I think it doesn't matter

**Comment by alexhtech** [comment]
@gilesbutler,  @oleeeg
I have tested for me and add DevTools for current project and I see that DevTools doesn't appear in my production build

```
...
let DevTools

if (process.env.NODE_ENV !== 'production') {
    require('mst-middlewares').connectReduxDevtools(require('remotedev'), store)
    DevTools = require('mobx-react-devtools').default
}


defaults.baseUrl = APP_API_BASE_URL


const render = App => {
    App({history, store}).then(result => {
        ReactDOM.render(
            <AppContainer>
                <React.Fragment>
                    {DevTools && <DevTools/>}
                    {result}
                </React.Fragment>
            </AppContainer>,
            document.getElementById('react-root')
        )
    })
}
...
```

Have you probably imported this package in another place ? And it doesn't work for you...

**Comment by alexhtech** [comment]
also you make sure that process.env.NODE_ENV === 'production' while you build production package

**Comment by moos** [comment]
@gilesbutler I noticed DevTools creeping into my prod build as well.  Turns out you can't dereference the key expression -- it must be in-place.
```js
// wrong:
let DEVMODE = process.env.NODE_ENV !== 'production';
if (DEVMODE) {
  var DevTools = require('mobx-react-devtools').default;
}
```
will still include it in the build, but:
```js
// right:
if (process.env.NODE_ENV !== 'production') {
  var DevTools = require('mobx-react-devtools').default;
}
```
will not.  Mystery solved!

**Comment by gilesbutler** [comment]
Awesome! Only just got back to this so really appreciate your help @alexolefirenko and @moos!! Thank you.

Your solutions worked, I ended up getting an error from Flow afterwords though as it was looking for a React element. So I went with this solution in the end...
```
const { Fragment } = React;

const Devtools = process.env.NODE_ENV !== "production" ? require("mobx-react-devtools").default : Fragment;
```

Then I can just use `<Devtools />` in my render method.

**Comment by hyperknot** [comment]
@gilesbutler thanks for your super clean solution! I've checked and it is indeed not included in the production bundle this way! I believe your solution should be in the readme actually!

**Comment by johnnyreilly** [comment]
I spent today digging through our webpack 4 config trying to work out why a compiled bundle contained code like this:

```
if("production"!==e.env.NODE_ENV){
```

My expectation was that with webpack 4 and `'mode': 'production'` this meant that behind the scenes all `process.env.NODE_ENV` statements should be converted to `'production'` and consequently Uglify would automatically get its groove on with the remaining `if("production"!=="production") ...` and strip the code.

It seemed that was not the case.  I was seeing (regrettably) undead code.  And who here actually likes the undead? 

It turns out that the way you use `mobx-react-devtools` reliably makes the difference.  @gilesbutler's solution is... well the solution!

On a dummy project I tried this:

```
import * as React from 'react';
import { Layout } from './components/layout';
import DevTools from 'mobx-react-devtools';

export const App: React.SFC<{}> = _props => (
    <div className="ui container">
        <Layout />
        {process.env.NODE_ENV !== 'production' ? <DevTools position={{ bottom: 20, right: 20 }} /> : null}
    </div>
);
```

And got a build size of 311kb.  Then I tried this:

```
import * as React from 'react';
import { Layout } from './components/layout';
const { Fragment } = React;

const DevTools = process.env.NODE_ENV !== 'production' ? require('mobx-react-devtools').default : Fragment;

export const App: React.SFC<{}> = _props => (
    <div className="ui container">
        <Layout />
        <DevTools position={{ bottom: 20, right: 20 }} />
    </div>
);
```

And got a build size of 191kb.  That's a saving of 120kb!

I think @hyperknot's suggestion of changing the advice in the README is a good one.  I'd be happy to submit a docs PR if that would be appreciated?

**Comment by Jessidhia** [comment]
To rephrase what "dereference the key expression" means; the access to `process.env.NODE_ENV` is itself converted to what you put in DefinePlugin, or webpack@4's mode, but webpack/uglify don't know or care about what happens to the value after it's put in a variable.

All your checks for `process.env.NODE_ENV !== 'production'` must be repeated on every place where you want compile-time branching.

An alternative to repetitive writing is to use `new webpack.DefinePlugin({ __DEV__: '(process.env.NODE_ENV !== "production")' })`. That way you use `__DEV__` as if it was a global.

(Note that, on webpack < 4, that plugin has to run before the `DefinePlugin` that defines `process.env.NODE_ENV`, or you can just define it directly to `true` / `false` with the result of the comparison)

**Comment by johnnyreilly** [comment]
Good suggestion @kovensky - think I might use that. I've turned my issue above into a blog post to try and spread the word; yesterday was a painful day and I want to save others from the ickyness... https://blog.johnnyreilly.com/2018/03/its-not-dead-2-mobx-react-devtools-and-the-undead.html

**Comment by mweststrate** [comment]
In 6.0.0 and up, the package is now marked as side-effect free, which means that if you import the devtools, but don't render them (for example because you are checking process.env.NODE_ENV around your rendering), the package won't be included in the build. Hope that helps!

**Comment by FoxWhite** [comment]
ver. 6.0.3:
```
import DevTools from 'mobx-react-devtools'
...
      <MyComponent>
      {IS_DEV_ENV && <DevTools />}
</MyComponent>
 ```
still gets me mobx-react-devtools in bundle.js.
@gilesbutler's solution works well

**Comment by bel0v** [comment]
ver. 6.0.3:
```
import DevTools from 'mobx-react-devtools'
...
<MyComponent>
  {IS_DEV_ENV && <DevTools />}
</MyComponent>
```
still gets me mobx-react-devtools in bundle.js.
@gilesbutler's solution works well

**Comment by nathanbirrell** [comment]
Should we mention this in the readme?

**Comment by marianban** [comment]
In case of React 16.6.0 you can use lazy to conditionally import mobx-react-devtools:

``` 
const DevTools = lazy(() =>
  process.env.NODE_ENV === "production"
    ? Promise.resolve({ default: () => null })
    :  (import("mobx-react-devtools") as any)
);
```
then wrap it with Suspense in render:
```
<Suspense fallback={null}>
  <DevTools />
</Suspense>
```
@pdeva condition fixed, thanks for pointing out the mistake

**Comment by pdeva** [comment]
@marianban the condition in your example need to be reversed:

```javascript
const DevTools = lazy(() =>
  process.env.NODE_ENV === "production"
    ? Promise.resolve({ default: () => null }): (import("mobx-react-devtools") as any)
);
```

otherwise you will load dev tool *in* the production build
