### ISSUE TITLE
Use devtools in React Native with Mobx State Tree

### ISSUE THREAD

**Issue by alexlevy0** [mobxjs/mobx-react-devtools#69]
Hello,

I'm trying to use mobx-remotedev with React Native and MobX-State-Tree but I don't know how to do. 
I tried with ```export default remotedev(AppStore, { global: true, remote: true })``` in my rootStore but I get an error ```Unhandled JS Exception: Cannot read property 'create' of undefined``` cause I create the tree with ```const appStore = AppStore.create({ users: {} }, { logger: logger })``` 

Can you orient me?

Thanks for readding

**Comment by mweststrate** [comment]
Note that this isn't the `mobx-remotedev` package ;-). Which can be found here: https://github.com/zalmoxisus/mobx-remotedev

The mobx-react-devtools (this repo) are specifically geared to DOM rendering (unlike remote dev), and offers fancy in-DOM visualization of updates. 

Note that it is even possible to use generic Redux based devtools like demonstrated here: https://github.com/mobxjs/mobx-state-tree/blob/master/examples/todomvc/src/index.js#L23

cc @zalmoxisus
