### ISSUE TITLE
Strange Popup

### ISSUE THREAD

**Issue by nodece** [mobxjs/mobx-react-devtools#74]
when id is 2 ，I don't know why this window appears。
Click Add button， id will Increment。
I want know This is my Program Problem or Friendly Debug Tool Problem。
![image](https://user-images.githubusercontent.com/16235121/31241109-767dbd62-aa35-11e7-8beb-47489854d098.png)

part of the code
```
// mobx log
setLogEnabled(true)
setUpdatesEnabled(true)
setGraphEnabled(true)


//TestStore
export default class TestStore {
  @observable public id: number = 1
  @action
  public async updateId() {
    this.id++
  }
}

// view
@observer
export default class Main extends React.Component <{ testStore ?: TestStore }, {}> {
  public render() {
    return (
      <div>
        {JSON.stringify(this.props.testStore)}
        <button onClick={() => this.props.testStore.updateId()}>Add</button>
      </div>
    )
  }
}
```

**Comment by andykog** [comment]
@nodece, `setGraphEnabled(true)` starts picking a component for dependencies inspector. Just remove that line.
