### ISSUE TITLE
"#undefined" when logging to the console or visualizing the tree of components 

### ISSUE THREAD

**Issue by carlosagsmendes** [mobxjs/mobx-react-devtools#76]
Hi there, 

I've installed the devtools but I'm getting `#undefined` entries both on the console or when visualizing the tree of components: 

<img width="835" alt="mobx-devtools" src="https://user-images.githubusercontent.com/1224078/32985630-380a8d72-ccb7-11e7-9f65-48dff2360859.png">

<img width="323" alt="mobx-inspect" src="https://user-images.githubusercontent.com/1224078/32985658-afc88954-ccb7-11e7-8cdd-d6f0f4e011d6.png">

Is this a bug or I'm I missing something?

Thanks in advance

**Comment by flakmonkey** [comment]
I believe this is because React has deprecated the `_rootNodeID` property on `_reactInternalInstance`. `mobx-react` attempts to capture this value in `index.module.js:686`.

**Comment by mweststrate** [comment]
Should be fixed when upgrading both `mobx-react` and `mobx-react-devtools` to the latest
