### ISSUE TITLE
It's too difficult to find error in 'action'

### ISSUE THREAD

**Issue by wang12124468** [mobxjs/mobx-react-devtools#77]
if a error is in 'action'， I must open the ‘action’ in 'console' to see the error。

**Comment by mweststrate** [comment]
Sadly can't really change this afaik, if tracing is enabled, we use grouping in the console logs, which means that anything that is printed to the console when during a group, will be printed inside the group, regardless where it is coming from. But if you are debugging anyway, consider using break-on-error to find exceptions, rather then the console.
