### ISSUE TITLE
I am getting an error after upgrading to latest mobx

### ISSUE THREAD

**Issue by richtera** [mobxjs/mobx-react-devtools#84]
https://github.com/mobxjs/mobx-react-devtools/blob/1f8a998114cd5c7c1a92bdcb4580ce1e975ac7e3/src/consoleLogChange.js#L240

Is this pending to be fixed or is there a specific option I need to configure mobx with to expose the debug names?
Thanks
Andy

**Comment by nitelite** [comment]
Is there a version of the dev tools in the works, compatible with MobX 4?

**Comment by jacklinton** [comment]
No response on this yet? Hopefully it's because they're hard at work updating the library...

**Comment by mweststrate** [comment]
Don't worry, it's being worked on

Op zo 18 mrt. 2018 05:44 schreef Jack Linton <notifications@github.com>:

**Comment by andykog** [comment]
Published `mobx-react-devtools@5.0.0` compatible with `mobx@4`

**Comment by kalmi** [comment]
It gives a warning during install as the mobx peer dependency in package.json have not been updated, but otherwise works fine. Thanks!

**Comment by richtera** [comment]
It seems to work but I am getting a whole bunch of "undefined" reaction names and I don't quite know where they are coming from. There seems to be some names not being picked up in the tooling.

**Comment by andykog** [comment]
@kalmi, thanks, fixed in 5.0.1
@richtera, this is more related to mobx-react package, see https://github.com/mobxjs/mobx-react/pull/368
