### ISSUE TITLE
[mobx] 'extras' is no longer part of the public MobX api.

### ISSUE THREAD

**Issue by tsiq-swyx** [mobxjs/mobx-react-devtools#86]
hi team!

I have an issue.

Here is my error messages:

```
Error
[mobx] 'extras' is no longer part of the public MobX api. Please consult the changelog to find out where this functionality went
▶ 11 stack frames were collapsed.
TodoListClass.onSubmit
/src/todolist.js:9:29
   6 | 
   7 | export class TodoListClass {
   8 |   items = ["get milk"]; // observable array
>  9 |   onSubmit = e => this.items.push(e); // action
     |                             ^
  10 | }
  11 | decorate(TodoListClass, { items: observable, onSubmit: action });
  12 | 
View compiled
▶ 2 stack frames were collapsed.
onSubmit
/src/todolist.js:34:17
  31 | <form
  32 |   onSubmit={e => {
  33 |     e.preventDefault();
> 34 |     list.onSubmit(this.input.value);
     |         ^
  35 |     this.input.value = "";
  36 |   }}
  37 | >
View compiled

```

![image](https://user-images.githubusercontent.com/35976578/37550320-9ad01bd2-2961-11e8-8891-fea85380b2b0.png)

Here is the codesandbox:  https://codesandbox.io/s/20lv7n3kvn just try to submit text in any box to see the error

what i'm trying to do here is to `decorate` my `onSubmit` with an `action` or `action.bound`. i expected 
it to work but got this opaque error. checking the changelog showed nothing.

## State the versions of MobX and relevant libraries. Which browser / node / ... version?

latest chrome, and the deps are in the codesandbox:

![image](https://user-images.githubusercontent.com/35976578/37550340-e5cc5eac-2961-11e8-9056-3079be0424fd.png)

please let me know what I should do. thank you!

**Comment by andykog** [comment]
Published `mobx-react-devtools@5.0.0` compatible with `mobx@4`

**Comment by tsiq-swyx** [comment]
whoo! thank you!

**Comment by mweststrate** [comment]
@tsiq-swyx would you mind updating that in the blog post ;-)?

**Comment by mweststrate** [comment]
Also notice that my name is spelled "Michel Weststrate" ;-)

**Comment by tsiq-swyx** [comment]
oops sorry, will fix!

i will find time this week to go back and fix up the rest of the blogpost. takes a lot of time to set up the examples correctly :)

**Comment by roots-ai** [comment]
This is not resolving the issue for us "mobx-react-devtools@5.0.0"
