### ISSUE TITLE
Reaction "undefined"

### ISSUE THREAD

**Issue by singggum3b** [mobxjs/mobx-react-devtools#89]
With mobx v 5.0.1, all reaction name is missing
Format of the change object have been changed.

**Comment by otroboe** [comment]
Any news from that ?
I'm new to mobx and I started with the version 5, so I don't know if I'm doing something wrong with some of my `reaction 'undefined'`.

**Comment by spector32** [comment]
Same here!

**Comment by jasonblalock** [comment]
I'm seeing the same thing in mobx 4.3.1 so I'm thinking it's not a v4 vs v5 issue.

**Comment by Lyfme** [comment]
so？where's the solution

**Comment by kasper573** [comment]
I also see the same issue in mobx 4.3.1.

**Comment by noah79** [comment]
This is extremely annoying.  I guess I should have waited to upgrade...

**Comment by noah79** [comment]
I'm trying to debug application slowness and the mobx devtools have gone from extremely useful to buggy and broken.  Please fix!

**Comment by mweststrate** [comment]
Note that the browser plugin version of this package is already to date!
I'm not entirely sure if this lib still adds value given the browser
plugins?

Op di 10 jul. 2018 18:20 schreef Noah Shipley <notifications@github.com>:

**Comment by mweststrate** [comment]
Fixed and released as `mobx-react-devtools@6.0.1`
