### ISSUE TITLE
Show dependency tree breaks when attempting to use MobX v5

### ISSUE THREAD

**Issue by sallas** [mobxjs/mobx-react-devtools#91]
Mobx v5 isn't officially supported by this package yet but I wanted to start a conversation about the biggest breaking change I found when upgrading.

> .$mobx property has been dropped from all observables and replaced by a Symbol. Instead of using x.$mobx.name, use import { $mobx } from "mobx"; x[$mobx].name etc.

This change breaks here:
https://github.com/mobxjs/mobx-react-devtools/blob/master/src/globalStore.js#L113

mobx-react solved this while keeping it backwards compatible in this commit:
https://github.com/mobxjs/mobx-react/commit/486f078e2dc1f164e9f814ebf0f22ad6374c6ff1

**Comment by mweststrate** [comment]
Fixed and released as `mobx-react-devtools@6.0.1`
